### ISSUE TITLE
The link to download the extension is unavailable

### ISSUE THREAD

**Issue by cheahph** [thingworx-field-work/3DChartWidgetStudio#1]
http://roicentersvn.ptcnet.ptc.com/placatus/Studio3DChartJsWidget/releases is unavailable.

**Comment by BogdanMihaiciuc** [comment]
For this extension, you can just download the entire repo and place it in a folder in Studio's extensions folder. The built package is really just a zip of the repo.

**Comment by stefan-lacatus** [comment]
Clarified download process in 678adb54480d20a8c15d3b3f2fe2baa41ace1828
